<a href="https://colab.research.google.com/github/bengsoon/predictive-maintenance/blob/master/Predictive_Maintenance_BC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install scikit-learn==0.23.1
!pip install imbalanced-learn==0.7.0

     |████████████████████████████████| 6.8MB 6.9MB/s 
  Found existing installation: scikit-learn 0.22.2.post1
    Uninstalling scikit-learn-0.22.2.post1:
      Successfully uninstalled scikit-learn-0.22.2.post1
     |████████████████████████████████| 174kB 5.1MB/s 
  Found existing installation: imbalanced-learn 0.4.3
    Uninstalling imbalanced-learn-0.4.3:
      Successfully uninstalled imbalanced-learn-0.4.3


In [ ]:
!pip install plotly --upgrade
!pip install chart-studio --upgrade

     |████████████████████████████████| 13.2MB 228kB/s 
  Found existing installation: plotly 4.4.1
    Uninstalling plotly-4.4.1:
      Successfully uninstalled plotly-4.4.1
     |████████████████████████████████| 71kB 3.9MB/s 


In [ ]:
import chart_studio.plotly as py
import plotly.graph_objs as go
import plotly
import pandas as pd
import numpy as np
from imblearn.over_sampling import SMOTE
from imblearn.over_sampling import SMOTENC
from sklearn import metrics

from sklearn.preprocessing import LabelEncoder

import xgboost as xgb
from xgboost.sklearn import XGBClassifier

import types

In [ ]:
from pathlib import Path
import os
import matplotlib.pyplot as plt

In [ ]:
path = Path("/content/drive/MyDrive/Colab_Notebooks/Predictive_Maintenance")
os.listdir(path)

['Predictive_Maintenance.ipynb',
 'ai4i2020.csv',
 'df_for_export-2.csv',
 'equipment_failure_data_2.csv',
 'equipment_failure_data_1.csv',
 '.ipynb_checkpoints',
 'machine_failure_prediction',
 'equipment_failure_data_2.csv.1',
 'equipment_failure_data_1.csv.1',
 'df_with_flipper',
 'data_with_rolling_spikes',
 'Machine Learning for  Equipment Maintenance - Pub.ipynb']

In [ ]:
#Import the second half from github
# os.chdir(path)
# !wget https://raw.githubusercontent.com/shadgriffin/machine_failure/master/equipment_failure_data_2.csv
# !wget https://raw.githubusercontent.com/shadgriffin/machine_failure/master/equipment_failure_data_1.csv

--2021-06-18 03:25:32--  https://raw.githubusercontent.com/shadgriffin/machine_failure/master/equipment_failure_data_2.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11762512 (11M) [text/plain]
Saving to: ‘equipment_failure_data_2.csv.1’

equipment_failure_d 100%[===================>]  11.22M  23.4MB/s    in 0.5s    

2021-06-18 03:25:34 (23.4 MB/s) - ‘equipment_failure_data_2.csv.1’ saved [11762512/11762512]

--2021-06-18 03:25:34--  https://raw.githubusercontent.com/shadgriffin/machine_failure/master/equipment_failure_data_1.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
H

In [ ]:
df_1 = pd.read_csv(path / "equipment_failure_data_1.csv", parse_dates=True); df_1.head()

ID     DATE REGION_CLUSTER  ... EQUIPMENT_FAILURE   S8  AGE_OF_EQUIPMENT
0  100001  12/2/14              G  ...                 0  0.0               880
1  100001  12/3/14              G  ...                 0  0.0               881
2  100001  12/4/14              G  ...                 0  0.0               882
3  100001  12/5/14              G  ...                 0  0.0               883
4  100001  12/6/14              G  ...                 0  0.0               884

[5 rows x 16 columns]

In [ ]:
df_1.describe()

ID     WELL_GROUP  ...             S8  AGE_OF_EQUIPMENT
count  149855.000000  149855.000000  ...  149855.000000     149855.000000
mean   100320.419512       2.497561  ...     117.481750       2751.146341
std       178.503502       1.093775  ...     204.107481       3368.354905
min    100001.000000       1.000000  ...     -16.490000          0.000000
25%    100164.000000       2.000000  ...       8.660000        755.000000
50%    100328.000000       2.000000  ...      44.320000       1143.000000
75%    100472.000000       3.000000  ...     135.080000       3224.500000
max    100612.000000       4.000000  ...    1824.960000      15170.000000

[8 rows x 12 columns]

In [ ]:
print("Min date", df_1["DATE"].min(), ", Max Date: ", df_1["DATE"].max())

Min date 1/1/15 , Max Date:  9/9/16


In [ ]:
df_2 = pd.read_csv(path / "equipment_failure_data_2.csv", parse_dates=True); df_2.head()

ID     DATE REGION_CLUSTER  ... EQUIPMENT_FAILURE   S8  AGE_OF_EQUIPMENT
0  100002  12/2/14              D  ...                 0  0.0               820
1  100002  12/3/14              D  ...                 0  0.0               821
2  100002  12/4/14              D  ...                 0  0.0               822
3  100002  12/5/14              D  ...                 0  0.0               823
4  100002  12/6/14              D  ...                 0  0.0               824

[5 rows x 16 columns]

In [ ]:
df_2.describe()

ID     WELL_GROUP  ...             S8  AGE_OF_EQUIPMENT
count  157896.000000  157896.000000  ...  157896.000000     157896.000000
mean   100301.722222       6.486111  ...     170.465310       2308.796296
std       176.206263       1.134395  ...     268.490199       2930.234090
min    100002.000000       5.000000  ...      -1.610000          0.000000
25%    100153.500000       5.000000  ...       9.765110        691.000000
50%    100288.500000       6.000000  ...      61.010000       1084.000000
75%    100459.250000       8.000000  ...     204.392500       2328.000000
max    100617.000000       8.000000  ...    2068.110000      14610.000000

[8 rows x 12 columns]

In [ ]:
print("Min date", df_2["DATE"].min(), ", Max Date: ", df_2["DATE"].max())

Min date 1/1/15 , Max Date:  9/9/16


In [ ]:
# concatenating the two df's

df = pd.concat([df_1, df_2])

In [ ]:

df.shape

(307751, 16)

In [ ]:
df.head()

ID     DATE REGION_CLUSTER  ... EQUIPMENT_FAILURE   S8  AGE_OF_EQUIPMENT
0  100001  12/2/14              G  ...                 0  0.0               880
1  100001  12/3/14              G  ...                 0  0.0               881
2  100001  12/4/14              G  ...                 0  0.0               882
3  100001  12/5/14              G  ...                 0  0.0               883
4  100001  12/6/14              G  ...                 0  0.0               884

[5 rows x 16 columns]

ID — ID field that represents a specific machine.

DATE — The date of the observation.

REGION_CLUSTER — a field that represents the region in which the machine resides.

MAINTENANCE_VENDOR — a field that represents the company that provides maintenance and service to the machine.

MANUFACTURER — the company that manufactured the equipment in question.

WELL_GROUP — a field representing the type of machine.

EQUIPMENT_AGE — Age of the machine, in days.

S15 — A Sensor Value.

S17 — A Sensor Value.

S13 — A Sensor Value.

S16 — A Sensor Value.

S19 — A Sensor Value.

S18 — A Sensor Value.

S8 — A Sensor Value.

EQUIPMENT_FAILURE — A ‘1’ means that the equipment failed. A ‘0’ means the equipment did not fail.

Our first goal in this exercise is to build a model that predicts equipment failure. In other words, we will use the other variables in the data frame to predict EQUIPMENT_FAILURE

In [ ]:
df.describe()

ID     WELL_GROUP  ...             S8  AGE_OF_EQUIPMENT
count  307751.000000  307751.000000  ...  307751.000000     307751.000000
mean   100310.826603       4.543943  ...     144.665715       2524.192399
std       177.574390       2.284121  ...     240.773926       3158.930976
min    100001.000000       1.000000  ...     -16.490000          0.000000
25%    100161.000000       3.000000  ...       9.250000        721.000000
50%    100311.000000       5.000000  ...      53.080000       1113.000000
75%    100467.000000       6.000000  ...     165.092608       2784.000000
max    100617.000000       8.000000  ...    2068.110000      15170.000000

[8 rows x 12 columns]

There are 421 machines

In [ ]:
print("Shape of the machine ID data: ", pd.DataFrame(df.groupby(["ID"]).agg(["count"])).shape)

Shape of the machine ID data:  (421, 15)


There are  unique dates

In [ ]:
print("Shape of the dates data: ", pd.DataFrame(df.groupby(["DATE"]).agg(["count"])).shape)

Shape of the dates data:  (731, 15)


We should have the same number of rows as 421 machines X 731 unique date entries

In [ ]:
421 * 731 == df.shape[0]

True

Therefore there shouldn't be any duplicates in the dataset..

In [ ]:
df.duplicated().sum(axis=0)

0

What about null values?

In [ ]:
df.isnull().sum(axis=0)

ID                    0
DATE                  0
REGION_CLUSTER        0
MAINTENANCE_VENDOR    0
MANUFACTURER          0
WELL_GROUP            0
S15                   0
S17                   0
S13                   0
S5                    0
S16                   0
S19                   0
S18                   0
EQUIPMENT_FAILURE     0
S8                    0
AGE_OF_EQUIPMENT      0
dtype: int64

Let's look at the distribution of the "EQUIPMENT_FAILURE" data... it seems that we do not have enough failure data (, which makes our dataset quite imbalanced.

which is quite common in reality (who wants to break their machines anyway?)

In [ ]:
failure = pd.DataFrame(df.groupby(["EQUIPMENT_FAILURE"])["ID"].agg(["count"]));
failure["%"] = round(failure["count"]/failure["count"].sum()*100, 2);
failure

count      %
EQUIPMENT_FAILURE               
0                  307330  99.86
1                     421   0.14

In [ ]:
df.corr(method="pearson")

ID    WELL_GROUP  ...        S8  AGE_OF_EQUIPMENT
ID                 1.000000e+00 -3.744075e-02  ...  0.037107          0.021574
WELL_GROUP        -3.744075e-02  1.000000e+00  ...  0.089935         -0.059788
S15               -3.529531e-02  4.963763e-02  ...  0.330548          0.024427
S17                2.676294e-02 -6.582945e-02  ... -0.334659         -0.019681
S13               -3.778625e-02 -6.932946e-02  ... -0.048435          0.033191
S5                 9.999313e-03  7.193471e-03  ...  0.562171          0.034668
S16                5.304853e-02  1.466090e-02  ... -0.022518          0.018336
S19               -4.066430e-02  6.717403e-02  ...  0.186710         -0.026847
S18                3.697739e-02  9.105041e-02  ...  0.856692         -0.027915
EQUIPMENT_FAILURE  2.959871e-18  7.048348e-17  ...  0.006517          0.000473
S8                 3.710678e-02  8.993457e-02  ...  1.000000         -0.025545
AGE_OF_EQUIPMENT   2.157369e-02 -5.978772e-02  ... -0.025545          1.000000

[12 rows x 12 columns]

In [ ]:
# def scatter(df, x, cols, figsize=(20,12)):
#   ''' to create a multiple scatter plots filtered for each feature.
#   Input:
#     - df: name of the dataframe (dataframe)
#     - x: column name of the dependent variable (str)
#     - cols: names of the columns to be plotted against dependent variable (list)
#     - figsize: dimension of the figure (tuple, default: (20,12))

#   Output: 2-column scatter plots for each of the columns specified for a dataframe filtered to the well against date
#   ''' 
#   # setting up the subplot
#   n_plots = len(cols) + 1
#   plt.figure(figsize=figsize)

#   for i, col in enumerate(cols):
#       data = df
#       plt.subplot(n_plots//2, 2, i+1)
#       plt.scatter(y = data[col], x = data[x])
#       plt.title("{} vs {}".format(col)) 
#       plt.xlim([data[y].min(), data[y].max()])
#   plt.tight_layout()

In [ ]:
df.columns

Index(['ID', 'DATE', 'REGION_CLUSTER', 'MAINTENANCE_VENDOR', 'MANUFACTURER',
       'WELL_GROUP', 'S15', 'S17', 'S13', 'S5', 'S16', 'S19', 'S18',
       'EQUIPMENT_FAILURE', 'S8', 'AGE_OF_EQUIPMENT'],
      dtype='object')

In [ ]:
df.head()

ID     DATE REGION_CLUSTER  ... EQUIPMENT_FAILURE   S8  AGE_OF_EQUIPMENT
0  100001  12/2/14              G  ...                 0  0.0               880
1  100001  12/3/14              G  ...                 0  0.0               881
2  100001  12/4/14              G  ...                 0  0.0               882
3  100001  12/5/14              G  ...                 0  0.0               883
4  100001  12/6/14              G  ...                 0  0.0               884

[5 rows x 16 columns]

In [ ]:
df.REGION_CLUSTER.unique()

array(['G', 'C', 'H', 'E', 'A', 'B', 'D', 'F'], dtype=object)

In [ ]:
df.MANUFACTURER.unique()

array(['Y', 'T', 'X', 'S', 'Q', 'Z', 'V', 'W', 'U', 'R'], dtype=object)

In [ ]:
df.MAINTENANCE_VENDOR.unique()

array(['O', 'L', 'M', 'K', 'J', 'I', 'N', 'P'], dtype=object)

In [ ]:
df["DATE"] = pd.to_datetime(df["DATE"])

In [ ]:
# sorting it by ID first and then DATE
df = df.sort_values(by=["ID", "DATE"], ascending=[True,True])

In [ ]:
df.head(200)

ID       DATE REGION_CLUSTER  ...         S8 AGE_OF_EQUIPMENT  flipper
0    100001 2014-12-02              G  ...   0.000000              880        1
1    100001 2014-12-03              G  ...   0.000000              881        0
2    100001 2014-12-04              G  ...   0.000000              882        0
3    100001 2014-12-05              G  ...   0.000000              883        0
4    100001 2014-12-06              G  ...   0.000000              884        0
..      ...        ...            ...  ...        ...              ...      ...
195  100001 2015-06-15              G  ...  57.840833             1075        0
196  100001 2015-06-16              G  ...  58.521739             1076        0
197  100001 2015-06-17              G  ...  51.780000             1077        0
198  100001 2015-06-18              G  ...  44.430000             1078        0
199  100001 2015-06-19              G  ...  50.910000             1079        0

[200 rows x 17 columns]

In [ ]:
df[df.flipper==1]

ID       DATE REGION_CLUSTER  ...          S8 AGE_OF_EQUIPMENT  flipper
0       100001 2014-12-02              G  ...    0.000000              880        1
0       100002 2014-12-02              D  ...    0.000000              820        1
731     100003 2014-12-02              C  ...    0.000000              400        1
731     100006 2014-12-02              B  ...    0.000000              980        1
1462    100007 2014-12-02              B  ...    0.000000             1380        1
...        ...        ...            ...  ...         ...              ...      ...
149124  100612 2014-12-02              H  ...  305.140000              360        1
154972  100613 2014-12-02              D  ...  472.380000              440        1
155703  100614 2014-12-02              A  ...    0.000000              740        1
156434  100616 2014-12-02              A  ...  106.870000              560        1
157165  100617 2014-12-02              C  ...   78.029167               80        1

[421 rows x 17 columns]

We want to create a "flipper" to indicate the row at which is the end of the machine 

In [ ]:
df["flipper"] = np.where((df["ID"] != df["ID"].shift(1)), 1, 0); df.head()

ID       DATE REGION_CLUSTER  ...   S8 AGE_OF_EQUIPMENT  flipper
0  100001 2014-12-02              G  ...  0.0              880        1
1  100001 2014-12-03              G  ...  0.0              881        0
2  100001 2014-12-04              G  ...  0.0              882        0
3  100001 2014-12-05              G  ...  0.0              883        0
4  100001 2014-12-06              G  ...  0.0              884        0

[5 rows x 17 columns]

In [ ]:
# save it so that we don't have to rerun all the above
df.to_pickle(path / "df_with_flipper")

In [ ]:
# load saved pickle data
data = pd.read_pickle(path / "df_with_flipper")

We will be using moving average to get the average value over the last "window" days. 

In [ ]:
# define the feature window to aggregate our sensor values
feature_window = 21

In [ ]:
startdate_df = data[data["flipper"] == 1][["DATE", "ID"]]
startdate_df

DATE      ID
0      2014-12-02  100001
731    2014-12-02  100002
1462   2014-12-02  100003
2193   2014-12-02  100006
2924   2014-12-02  100007
...           ...     ...
304096 2014-12-02  100612
304827 2014-12-02  100613
305558 2014-12-02  100614
306289 2014-12-02  100616
307020 2014-12-02  100617

[421 rows x 2 columns]

In [ ]:
startdate = startdate_df.rename(columns = {"DATE" : "START_DATE"})

In [ ]:
startdate

START_DATE      ID
0      2014-12-02  100001
0      2014-12-02  100002
731    2014-12-02  100003
731    2014-12-02  100006
1462   2014-12-02  100007
...           ...     ...
149124 2014-12-02  100612
154972 2014-12-02  100613
155703 2014-12-02  100614
156434 2014-12-02  100616
157165 2014-12-02  100617

[421 rows x 2 columns]

In [ ]:
data = pd.merge(data, startdate, on="ID", how="left")

In [ ]:
data.head(148)

ID       DATE REGION_CLUSTER  ... AGE_OF_EQUIPMENT flipper  START_DATE
0       100001 2014-12-02              G  ...              880       1  2014-12-02
1       100001 2014-12-03              G  ...              881       0  2014-12-02
2       100001 2014-12-04              G  ...              882       0  2014-12-02
3       100001 2014-12-05              G  ...              883       0  2014-12-02
4       100001 2014-12-06              G  ...              884       0  2014-12-02
...        ...        ...            ...  ...              ...     ...         ...
307746  100617 2016-11-27              C  ...              806       0  2014-12-02
307747  100617 2016-11-28              C  ...              807       0  2014-12-02
307748  100617 2016-11-29              C  ...              808       0  2014-12-02
307749  100617 2016-11-30              C  ...              809       0  2014-12-02
307750  100617 2016-12-01              C  ...              810       0  2014-12-02

[307751 rows x 18 columns]

In [ ]:
data["T"] = data["DATE"] - data["START_DATE"]
data["TIME_SINCE_START"] =  ( data["DATE"] - data["START_DATE"] ) / np.timedelta64(1, "D")
data["within_window"] = np.where( (data["TIME_SINCE_START"] < feature_window), 1, 0)
data.drop(columns=["T"], inplace=True)
data.head(25)

ID       DATE REGION_CLUSTER  ... S19_change S18_change  S8_change
0   100001 2014-12-02              G  ...   1.000000   1.000000        0.0
1   100001 2014-12-03              G  ...   1.000000   1.001239        0.0
2   100001 2014-12-04              G  ...   1.034483   1.002498        0.0
3   100001 2014-12-05              G  ...   1.025641   1.003079        0.0
4   100001 2014-12-06              G  ...   0.806452   1.003591        0.0
5   100001 2014-12-07              G  ...   0.833333   1.004264        0.0
6   100001 2014-12-08              G  ...   0.853659   1.005075        0.0
7   100001 2014-12-09              G  ...   1.526316   1.005059        0.0
8   100001 2014-12-10              G  ...   1.441989   1.005526        0.0
9   100001 2014-12-11              G  ...   1.542056   1.005393        0.0
10  100001 2014-12-12              G  ...   1.469636   1.006913        0.0
11  100001 2014-12-13              G  ...   1.414286   1.008996        0.0
12  100001 2014-12-14              G  ...   1.370607   1.011292        0.0
13  100001 2014-12-15              G  ...   1.335260   1.014327        0.0
14  100001 2014-12-16              G  ...   1.306069   1.016990        0.0
15  100001 2014-12-17              G  ...   1.281553   1.019002        0.0
16  100001 2014-12-18              G  ...   1.260674   4.741982        0.0
17  100001 2014-12-19              G  ...   1.242678   3.927833        0.0
18  100001 2014-12-20              G  ...   1.227006   3.406997        0.0
19  100001 2014-12-21              G  ...   1.213235   3.049336        0.0
20  100001 2014-12-22              G  ...   1.201040   2.773559        0.0
21  100001 2014-12-23              G  ...   1.000000   1.000000        0.0
22  100001 2014-12-24              G  ...   1.000000   1.000000        0.0
23  100001 2014-12-25              G  ...   1.000000   1.000000        0.0
24  100001 2014-12-26              G  ...   1.000000   1.000000        0.0

[25 rows x 60 columns]

In [ ]:
data.columns

Index(['ID', 'DATE', 'REGION_CLUSTER', 'MAINTENANCE_VENDOR', 'MANUFACTURER',
       'WELL_GROUP', 'S15', 'S17', 'S13', 'S5', 'S16', 'S19', 'S18',
       'EQUIPMENT_FAILURE', 'S8', 'AGE_OF_EQUIPMENT', 'flipper', 'START_DATE',
       'T', 'TIME_SINCE_START', 'not_yet'],
      dtype='object')

In [ ]:
sensors_name = ['S15', 'S17', 'S13', 'S5', 'S16', 'S19', 'S18',"S8"]

# create a rolling statistics for the sensor values
for sensor in sensors_name:
  data[sensor + str("_mean")] = np.where((data["within_window"] == 1), ( data[sensor].rolling(min_periods=1, window=feature_window).mean() ), data[sensor])
  data[sensor + str("_median")] = np.where((data["within_window"] == 1), ( data[sensor].rolling(min_periods=1, window=feature_window).median() ), data[sensor])
  data[sensor + str("_max")] = np.where((data["within_window"] == 1), ( data[sensor].rolling(min_periods=1, window=feature_window).max() ), data[sensor])
  data[sensor + str("_min")] = np.where((data["within_window"] == 1), ( data[sensor].rolling(min_periods=1, window=feature_window).min() ), data[sensor])

In [ ]:
data.head(25)

ID       DATE REGION_CLUSTER  ... S8_median S8_max  S8_min
0   100001 2014-12-02              G  ...       0.0    0.0     0.0
1   100001 2014-12-03              G  ...       0.0    0.0     0.0
2   100001 2014-12-04              G  ...       0.0    0.0     0.0
3   100001 2014-12-05              G  ...       0.0    0.0     0.0
4   100001 2014-12-06              G  ...       0.0    0.0     0.0
5   100001 2014-12-07              G  ...       0.0    0.0     0.0
6   100001 2014-12-08              G  ...       0.0    0.0     0.0
7   100001 2014-12-09              G  ...       0.0    0.0     0.0
8   100001 2014-12-10              G  ...       0.0    0.0     0.0
9   100001 2014-12-11              G  ...       0.0    0.0     0.0
10  100001 2014-12-12              G  ...       0.0    0.0     0.0
11  100001 2014-12-13              G  ...       0.0    0.0     0.0
12  100001 2014-12-14              G  ...       0.0    0.0     0.0
13  100001 2014-12-15              G  ...       0.0    0.0     0.0
14  100001 2014-12-16              G  ...       0.0    0.0     0.0
15  100001 2014-12-17              G  ...       0.0    0.0     0.0
16  100001 2014-12-18              G  ...       0.0    0.0     0.0
17  100001 2014-12-19              G  ...       0.0    0.0     0.0
18  100001 2014-12-20              G  ...       0.0    0.0     0.0
19  100001 2014-12-21              G  ...       0.0    0.0     0.0
20  100001 2014-12-22              G  ...       0.0    0.0     0.0
21  100001 2014-12-23              G  ...       0.0    0.0     0.0
22  100001 2014-12-24              G  ...       0.0    0.0     0.0
23  100001 2014-12-25              G  ...       0.0    0.0     0.0
24  100001 2014-12-26              G  ...       0.0    0.0     0.0

[25 rows x 53 columns]

Another useful thing to do is to detect sudden spikes in sensor values to show deviation from the average values..

In [ ]:
sensors_name = ['S15', 'S17', 'S13', 'S5', 'S16', 'S19', 'S18',"S8"]

# calculate fractional deviations from mean:
for sensor in sensors_name:
  data[sensor + str("_change")] = np.where( (data[sensor + str("_mean")] == 0 ), 0, ( data[sensor] / data[sensor + str("_mean")] ) )   # if mean = 0, then change is zero, otherwise sensor_value / sensor_mean_value

data.head(25)

ID       DATE REGION_CLUSTER  ... S19_change S18_change  S8_change
0   100001 2014-12-02              G  ...   1.000000   1.000000        0.0
1   100001 2014-12-03              G  ...   1.000000   1.001239        0.0
2   100001 2014-12-04              G  ...   1.034483   1.002498        0.0
3   100001 2014-12-05              G  ...   1.025641   1.003079        0.0
4   100001 2014-12-06              G  ...   0.806452   1.003591        0.0
5   100001 2014-12-07              G  ...   0.833333   1.004264        0.0
6   100001 2014-12-08              G  ...   0.853659   1.005075        0.0
7   100001 2014-12-09              G  ...   1.526316   1.005059        0.0
8   100001 2014-12-10              G  ...   1.441989   1.005526        0.0
9   100001 2014-12-11              G  ...   1.542056   1.005393        0.0
10  100001 2014-12-12              G  ...   1.469636   1.006913        0.0
11  100001 2014-12-13              G  ...   1.414286   1.008996        0.0
12  100001 2014-12-14              G  ...   1.370607   1.011292        0.0
13  100001 2014-12-15              G  ...   1.335260   1.014327        0.0
14  100001 2014-12-16              G  ...   1.306069   1.016990        0.0
15  100001 2014-12-17              G  ...   1.281553   1.019002        0.0
16  100001 2014-12-18              G  ...   1.260674   4.741982        0.0
17  100001 2014-12-19              G  ...   1.242678   3.927833        0.0
18  100001 2014-12-20              G  ...   1.227006   3.406997        0.0
19  100001 2014-12-21              G  ...   1.213235   3.049336        0.0
20  100001 2014-12-22              G  ...   1.201040   2.773559        0.0
21  100001 2014-12-23              G  ...   1.000000   1.000000        0.0
22  100001 2014-12-24              G  ...   1.000000   1.000000        0.0
23  100001 2014-12-25              G  ...   1.000000   1.000000        0.0
24  100001 2014-12-26              G  ...   1.000000   1.000000        0.0

[25 rows x 61 columns]

In [ ]:
#savepoint! 

data.to_pickle(path / "data_with_rolling_spikes")

In [ ]:
# load saved pickle

data = pd.read_pickle(path / "data_with_rolling_spikes")

# Dealing with Uneven Data Distributions

Remember that our failure data consists only about 0.14% of our whole dataset, which is extremely low and the ML algorithm will not be able to learn it very well.

This is very common, considering that machines are usually made to last and we don't typically run the machines to failure.

To ameliorate the issue of imbalance in the dataset, one of the ways is to augment the failure data into a window of time, in which case we will call it `target_window`. 

This `target_window` is the number of days prior to the failure time that we will consider to be "failed". For example, if we set `target_window` to 28 days, that means the machine was already "failed" 28 prior to the actual failure day.

In [ ]:
# set the target_window days

target_window = 28

In [ ]:
# create a dataframe with only the failure date for each ID 

data = data.sort_values(by=["ID", "DATE"], ascending=[True, True])

failure_df = data[data["EQUIPMENT_FAILURE"] == 1][["DATE", "ID"]];
failure_df = failure_df.rename(columns = {"DATE" : "FAILURE_DATE"})
failure_df

FAILURE_DATE      ID
143      2015-04-24  100001
1060     2015-10-27  100002
2183     2016-11-22  100003
2754     2016-06-15  100006
2984     2015-01-31  100007
...             ...     ...
304742   2016-09-08  100612
305182   2015-11-22  100613
306127   2016-06-23  100614
306848   2016-06-13  100616
307679   2016-09-21  100617

[421 rows x 2 columns]

In [ ]:
# merge to the main dataframe

data = data.sort_values(by=["ID"], ascending=True)
failure_df = failure_df.sort_values(by=["ID"], ascending=True)

data = pd.merge(data, failure_df, how="left", on = "ID")

In [ ]:
data.head()

ID       DATE REGION_CLUSTER  ... S18_change S8_change  FAILURE_DATE
0  100001 2014-12-02              G  ...        1.0       0.0    2015-04-24
1  100001 2016-03-29              G  ...        1.0       1.0    2015-04-24
2  100001 2016-03-30              G  ...        1.0       1.0    2015-04-24
3  100001 2016-03-31              G  ...        1.0       1.0    2015-04-24
4  100001 2016-04-01              G  ...        1.0       1.0    2015-04-24

[5 rows x 61 columns]

In [ ]:
data["FAILURE_DATE"] = pd.to_datetime(data["FAILURE_DATE"])
data["DATE"] = pd.to_datetime(data["DATE"])

data["TIME_TO_FAILURE"] = ( data["FAILURE_DATE"]  - data["DATE"] ) / np.timedelta64(1, 'D')
data = data.sort_values(by=['ID', 'DATE'], ascending=[True, True])
data.reset_index(inplace=True)

In [ ]:
data.head(148)

index      ID       DATE  ... S8_change FAILURE_DATE TIME_TO_FAILURE
0        0  100001 2014-12-02  ...       0.0   2015-04-24           143.0
1      549  100001 2014-12-03  ...       0.0   2015-04-24           142.0
2      483  100001 2014-12-04  ...       0.0   2015-04-24           141.0
3      484  100001 2014-12-05  ...       0.0   2015-04-24           140.0
4      485  100001 2014-12-06  ...       0.0   2015-04-24           139.0
..     ...     ...        ...  ...       ...          ...             ...
143    440  100001 2015-04-24  ...       0.0   2015-04-24             0.0
144    441  100001 2015-04-25  ...       0.0   2015-04-24            -1.0
145    442  100001 2015-04-26  ...       0.0   2015-04-24            -2.0
146    443  100001 2015-04-27  ...       0.0   2015-04-24            -3.0
147    444  100001 2015-04-28  ...       0.0   2015-04-24            -4.0

[148 rows x 63 columns]

Create a target variable `TARGET_FAILURE` that sets to 1 if `TIME_TO_FAILURE` < `target_window` (even when `EQUIPMENT_FAILURE` is still 0)


In [ ]:
# create the TARGET_FAILURE column

data["TARGET_FAILURE"] = np.where(( (data["TIME_TO_FAILURE"] < target_window) & (data["TIME_TO_FAILURE"] >= 0) ), 1, 0)

In [ ]:
data.head(148)

index      ID       DATE  ... FAILURE_DATE TIME_TO_FAILURE TARGET_FAILURE
0        0  100001 2014-12-02  ...   2015-04-24           143.0              0
1      549  100001 2014-12-03  ...   2015-04-24           142.0              0
2      483  100001 2014-12-04  ...   2015-04-24           141.0              0
3      484  100001 2014-12-05  ...   2015-04-24           140.0              0
4      485  100001 2014-12-06  ...   2015-04-24           139.0              0
..     ...     ...        ...  ...          ...             ...            ...
143    440  100001 2015-04-24  ...   2015-04-24             0.0              1
144    441  100001 2015-04-25  ...   2015-04-24            -1.0              0
145    442  100001 2015-04-26  ...   2015-04-24            -2.0              0
146    443  100001 2015-04-27  ...   2015-04-24            -3.0              0
147    444  100001 2015-04-28  ...   2015-04-24            -4.0              0

[148 rows x 64 columns]

In [ ]:
failure = pd.DataFrame(data.groupby(["TARGET_FAILURE"])["ID"].agg(["count"]));
failure["%"] = round(failure["count"]/failure["count"].sum()*100, 2);
failure

count      %
TARGET_FAILURE               
0               296011  96.19
1                11740   3.81

We have now improved our imbalance dataset a little bit by setting the target_failure within a "window" rather than a specific date. This is also useful for us because in reality, maintenance should be done ahead of time within a "window" rather than on the day of failure itself.

However, 3.8% of failure data is still relatively low for the whole dataset, so we can synthetically populate these failure data through statistical method called SMOTE, but we will perform it only on the training set. So we will have to perform splits on the dataset for training, validation and test sets. 

In [ ]:
#savepoint! 

data.to_pickle(path / "data_with_target_failure")

In [ ]:
# load picke
data = pd.read_pickle(path / "data_with_target_failure")

# Training, Cross Validation and Test Sets

Because the dataset came from the panel data (ie cross-sectional time series data, uniquely identified by machine `ID`), we need to avoid splitting the records from one single machine in all three sample datasets, in other words we should not randomize the sample of the records.

On the other hand, we randomly select IDs and place each of those machines in either training, validation or test sets.

In [ ]:
id_df = pd.DataFrame(data["ID"].unique(), columns = ["ID"])
id_df

ID
0    100001
1    100002
2    100003
3    100006
4    100007
..      ...
416  100612
417  100613
418  100614
419  100616
420  100617

[421 rows x 1 columns]

In [ ]:
# assign a random uniform probability to the machine ID's 
np.random.seed(42)
id_df["probability"] = (np.random.randint(0., 10000., id_df.shape[0]))/10000  # 10000 to make it floating point?

In [ ]:
id_df

ID  probability MODELING_SET
0    100001       0.7270         TEST
1    100002       0.0860     TRAINING
2    100003       0.5390   VALIDATION
3    100006       0.5191   VALIDATION
4    100007       0.5734   VALIDATION
..      ...          ...          ...
416  100612       0.4070   VALIDATION
417  100613       0.9662         TEST
418  100614       0.0580     TRAINING
419  100616       0.7004         TEST
420  100617       0.8130         TEST

[421 rows x 3 columns]

Let's give 35% of the probability to be the training set, 30% validation set and 35% test set.

In [ ]:
id_df["MODELING_SET"] = np.where( (id_df["probability"] <= 0.35), "TRAINING", np.where( (id_df["probability"] <= 0.65), "VALIDATION", "TEST" ) )

In [ ]:
id_df

ID  probability MODELING_SET
0    100001       0.7270         TEST
1    100002       0.0860     TRAINING
2    100003       0.5390   VALIDATION
3    100006       0.5191   VALIDATION
4    100007       0.5734   VALIDATION
..      ...          ...          ...
416  100612       0.4070   VALIDATION
417  100613       0.9662         TEST
418  100614       0.0580     TRAINING
419  100616       0.7004         TEST
420  100617       0.8130         TEST

[421 rows x 3 columns]

In [ ]:
id_sets = pd.DataFrame(id_df.groupby(["MODELING_SET"])["ID"].agg(["count"]));
id_sets["%"] = round(id_sets["count"]/id_sets["count"].sum()*100, 2);
id_sets

count      %
MODELING_SET              
TEST            149  35.39
TRAINING        146  34.68
VALIDATION      126  29.93

Let's merge `id_df` to our main `data`

In [ ]:
# sort the dataframes by "ID" first

id_df.sort_values(by=["ID"], ascending=True, inplace = True)
data.sort_values(by=["ID"], ascending=True, inplace= True)

In [ ]:
data = data.merge(id_df, how='left', on=['ID'])
data.tail(140)

index      ID       DATE  ... TARGET_FAILURE probability MODELING_SET
307611  307611  100617 2015-09-23  ...              0       0.813         TEST
307612  307612  100617 2015-09-02  ...              0       0.813         TEST
307613  307613  100617 2015-10-16  ...              0       0.813         TEST
307614  307614  100617 2015-10-18  ...              0       0.813         TEST
307615  307615  100617 2015-11-11  ...              0       0.813         TEST
...        ...     ...        ...  ...            ...         ...          ...
307746  307746  100617 2015-08-04  ...              0       0.813         TEST
307747  307747  100617 2015-08-05  ...              0       0.813         TEST
307748  307748  100617 2015-08-06  ...              0       0.813         TEST
307749  307749  100617 2015-08-08  ...              0       0.813         TEST
307750  307750  100617 2016-12-01  ...              0       0.813         TEST

[140 rows x 66 columns]

Let's see how many records for each modeling sets:

In [ ]:
id_sets = pd.DataFrame(data.groupby(["MODELING_SET"])["ID"].agg(["count"]));
id_sets["%"] = round(id_sets["count"]/id_sets["count"].sum()*100, 2);
id_sets

count      %
MODELING_SET               
TEST          108919  35.39
TRAINING      106726  34.68
VALIDATION     92106  29.93

In [ ]:
data.groupby(["MODELING_SET"])["TARGET_FAILURE"].sum()

MODELING_SET
TEST          4151
TRAINING      4071
VALIDATION    3518
Name: TARGET_FAILURE, dtype: int64

Create separate dataframe for train, validation and test sets

In [ ]:
data.shape

(307751, 66)

In [ ]:
data.columns

Index(['index', 'ID', 'DATE', 'REGION_CLUSTER', 'MAINTENANCE_VENDOR',
       'MANUFACTURER', 'WELL_GROUP', 'S15', 'S17', 'S13', 'S5', 'S16', 'S19',
       'S18', 'EQUIPMENT_FAILURE', 'S8', 'AGE_OF_EQUIPMENT', 'flipper',
       'START_DATE', 'TIME_SINCE_START', 'within_window', 'S15_mean',
       'S17_mean', 'S13_mean', 'S5_mean', 'S16_mean', 'S19_mean', 'S18_mean',
       'S8_mean', 'S15_median', 'S15_max', 'S15_min', 'S17_median', 'S17_max',
       'S17_min', 'S13_median', 'S13_max', 'S13_min', 'S5_median', 'S5_max',
       'S5_min', 'S16_median', 'S16_max', 'S16_min', 'S19_median', 'S19_max',
       'S19_min', 'S18_median', 'S18_max', 'S18_min', 'S8_median', 'S8_max',
       'S8_min', 'S15_change', 'S17_change', 'S13_change', 'S5_change',
       'S16_change', 'S19_change', 'S18_change', 'S8_change', 'FAILURE_DATE',
       'TIME_TO_FAILURE', 'TARGET_FAILURE', 'probability', 'MODELING_SET'],
      dtype='object')

In [ ]:
# setting up training dataset
df_train = data[data["MODELING_SET"] == "TRAINING"]
df_train = df_train.drop(columns = ["MODELING_SET", "probability", "START_DATE", "flipper", "TIME_TO_FAILURE"])
df_train.shape

(106726, 61)

In [ ]:
# create separate dataframe for training and test datasets. We will use this to tweak our models
df_train_test = data[data["MODELING_SET"] != "VALIDATION"]
df_train_test= df_train_test.drop(columns = ["MODELING_SET", "probability", "START_DATE", "flipper", "TIME_TO_FAILURE"])
df_train_test.shape

(215645, 61)

In [ ]:
# create a separate dataframe for all the data. We will use this to validate the model and compare accuracy for all groups
df_total = data.drop(columns=["MODELING_SET", "probability", "START_DATE", "flipper", "TIME_TO_FAILURE"])
df_total.shape

(307751, 61)

# Synthetic Minority Oversampling Technique (SMOTE)